"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*d(=lwu+w-+69)-3v86(qjp!2yircyw=zrny*hpwvfc6j97@0e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'consulta',
    'home',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['app/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configurações do SparQL
SPARQL_REQUEST_CONFIG = {
    'USER_AGENT': 'ConsultaApp/1.0 or localhost',
    'TIMEOUT': 10,
    'ENDPOINT': 'https://query.wikidata.org/sparql',
    'STATE_CODES': {
        'AC': 'Q40780',  # Acre
        'AL': 'Q40885',  # Alagoas
        'AP': 'Q40130',  # Amapá
        'AM': 'Q40040',  # Amazonas
        'BA': 'Q40430',  # Bahia
        'CE': 'Q40123',  # Ceará
        'DF': 'Q119158', # Distrito Federal
        'ES': 'Q43233',  # Espírito Santo
        'GO': 'Q41587',  # Goiás
        'MA': 'Q42362',  # Maranhão
        'MT': 'Q42824',  # Mato Grosso
        'MS': 'Q43319',  # Mato Grosso do Sul
        'MG': 'Q39109',  # Minas Gerais
        'PA': 'Q39517',  # Pará
        'PB': 'Q38088',  # Paraíba
        'PR': 'Q15499',  # Paraná
        'PE': 'Q40942',  # Pernambuco
        'PI': 'Q42722',  # Piauí
        'RJ': 'Q41428',  # Rio de Janeiro
        'RN': 'Q43255',  # Rio Grande do Norte
        'RS': 'Q40030',  # Rio Grande do Sul
        'RO': 'Q43235',  # Rondônia
        'RR': 'Q42508',  # Roraima
        'SC': 'Q41115',  # Santa Catarina
        'SP': 'Q175',    # São Paulo
        'SE': 'Q43783',  # Sergipe
        'TO': 'Q43695'   # Tocantins
    }
}


# Configurações da API do IBGE
API_IBGE_CONFIG = {
    'USER_AGENT': f'ConsultaApp/1.0 or localhost',
    'TIMEOUT': 10,
    'ENDPOINT': 'https://servicodados.ibge.gov.br/api/v1/localidades/estados', 
}


# Sigla de estado para requisições
STATE_UF = {'UF':'sp'.upper()}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
